using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpringScript : MonoBehaviour
{
    //K Constant in Hooke's Law https://en.wikipedia.org/wiki/Hooke%27s_law
    private float K = 1.5f;
    //x in Hooks'Law (distance travelled by the free end of the hook)
    private float x = 0;
    //Force in Hooks'Law (distance travelled by the free end of the hook)
    private float Fy = 0;
    
    public Rigidbody gameObjectRb = null;

    private float gravity = 9.8f;
    
    public bool IsCompressing = false;

    public Vector3 lastVelocity = new Vector3();

    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void Update()
    {
        CalculateCompression();
    }

    private void CalculateCompression()
    {
        //Calculate the compression force generated by the mass of the AttachedObject
        Fy = (gameObjectRb.velocity.y - lastVelocity.y) * gravity * Time.deltaTime;
        lastVelocity = gameObjectRb.velocity;
        gameObjectRb.transform.localScale = new Vector3(gameObject.transform.localScale.x, 1 - ((Fy > 0) ? Math.Min(Fy / K, 1.2f) : Math.Max(Fy / K, -0.2f)), gameObject.transform.localScale.z);
    }

    private void OnCollisionEnter(Collision collision)
    {
        if(collision.gameObject.layer == 0)
            IsCompressing = true;
    }

    private void OnCollisionExit(Collision collision)
    {
        if (collision.gameObject.layer == 0)
            IsCompressing = false;
    }
}
